Update styles.css for works section of the porfolio
EnixWord/My_Portfolio pull request #4
Opened 2022-12-03 20:46 UTC by EnixWord

### Highlights
In this **PR**, I worked on the following aspects of the project:
- Import project cards
- Utilize flexbox for styling
- Transform figma design into html and css properties

2022-12-03 21:00 UTC, mgmediaweb requested changes
Hi @EnixWord , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![work4](https://user-images.githubusercontent.com/41912912/205461916-23528200-5595-4f2b-980a-de199d72f931.gif)

## Highlights 💯 
- Professional-looking readme file. ✔️ 
- Clear and descriptive Pull Request. ✔️ 

## Required Changes ♻️

[ATENTION] Kindly, you did not present the project requirements, the WORKS area and the ABOUT section,

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-05 12:17 UTC, ha-manel requested changes
# STATUS: REQUIRED CHANGES ♻️

## Hi @EnixWord 👋 
Great job so far, There are some changes that need to be implemented in order to proceed to the next project 👍  

<img src="https://media3.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif"/>

## Highlights:  
* All tests passed ✔️
* Meaningful commit messages ✔️ 

## Required Changes:

- [ ] Kindly add the MIT file to your project, the link in the README file is broken 👍 

_Kindly check the comments below_


------
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-05 12:17 UTC, ha-manel commented on index.html
> +          <h1 class="header-text">About Myself</h1>
- [ ] Kindly change this `h1` tag to another `hx` tag like `h2`... There should be only one `h1` tag in a web page which is the main heading of that page 👍

2022-12-05 12:17 UTC, ha-manel commented on index.html
> +          </div>
- [ ] Kindly make this a `ul` `li` structure for semantic reasons, the final structure should look like this:
```
<ul>
  <li>Languages
    <ul>
       <li>JavaScript</li>
       ...
    </ul>
  </li>
  <li>Skills</li>
  .....
</ul>
```

2022-12-05 12:17 UTC, ha-manel commented on index.html
> +        </div>
- [ ] Kindly remove the `background-image` here to match the design in Figma 👍 
- [ ] Also please match the `background-color` of the page which is `#E5E5E5` then the project cards should be white `#fff` 💯 

## Your design:
![image](https://user-images.githubusercontent.com/50721479/205632832-429fa2f9-cffe-45b3-a8e0-fd71c9b59c56.png)

## Figma design:
![image](https://user-images.githubusercontent.com/50721479/205633008-c07e23f9-39ca-48dd-9668-09a92fde37db.png)

2022-12-05 12:17 UTC, ha-manel commented on index.html
> +                <li>JAVASCRIPT</li>
- [ ] Kindly change the text `color` of the technologies to match the design 👍 

## Your design:
![image](https://user-images.githubusercontent.com/50721479/205633529-607c705c-cbe9-4f89-a74e-a511a693b1b7.png)

## Figma design:
![image](https://user-images.githubusercontent.com/50721479/205633566-8db38eb0-3b52-4f40-aff6-cf7b0c3a7af0.png)

2022-12-05 12:17 UTC, ha-manel commented on index.html
> +          <div class="project-card flex">
- [ ] Kindly increase the space between the cards to match the design 👍 

## Your design:
![image](https://user-images.githubusercontent.com/50721479/205633774-27d23d26-1591-4fdd-8818-8e2e589df8f3.png)

## Figma design:
![image](https://user-images.githubusercontent.com/50721479/205633823-ebc74472-776e-4662-b7c1-f858bdbc4fc9.png)

2022-12-05 12:17 UTC, ha-manel commented on index.html
> +              <button>See Project</button>
- [ ] Kindly add button interaction styles just as shown in Figma 👍 

![image](https://user-images.githubusercontent.com/50721479/205634068-5544d243-3233-44e2-acd8-3d3d10d0c863.png)

2022-12-05 12:17 UTC, ha-manel commented on index.html
> +          <h1 class="header-text">About Myself</h1>
- [ ] Kindly remove the `border-radius` from the bottom of the works section and add it to the top right of the about section to match the design 👍 

## Your design:
![image](https://user-images.githubusercontent.com/50721479/205634480-f30dcb7a-cadc-43f7-a318-a9fb527c4b25.png)

## Figma design:
![image](https://user-images.githubusercontent.com/50721479/205634548-9cb0855d-e705-47fe-a84a-201f40cf1fd0.png)

2022-12-05 12:17 UTC, ha-manel commented on index.html
> +    <section class="project-section">
- [ ] Good job on using Flexbox to style the project cards 👍 As stated in the requirements kindly use `grid` for the big container of the works section to demonstrate the ability to work with both 💯

2022-12-05 17:50 UTC, algerina requested changes
Hi @EnixWord , 

You've done a good job fir 👏 💯 👍
There are some issues that you still need to work on to go to the next project but you are almost there! 

## Highlights
  -  No Linter errors 
  -  It was good to add the MIT license and update the Readme.
 

## Required Changes ♻️

- :red_square:  Kindly implement all the changes required by the previous reviewer.

## Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.




Cheers and Happy coding!👏👏👏

__Feel free to leave any questions or comments in the PR thread if something is not 100% clear.__

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
> As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).
___
_If anything seems to be unclear to you, reach out and ask anything by commenting on this Pull Request and mention me as [Algerina](https://github.com/algerina), I will receive a notification and will respond._

[GitHub](https://github.com/algerina) | [LinkedIn](https://linkedin.com/in/amel-khiri) | [Twitter](https://twitter.com/AmelQahwadji)

_Reviewed by [Amel Khiri ](https://github.com/algerina)_

2022-12-07 13:26 UTC, EnixWord commented on index.html
> +    <section class="project-section">
Thanks for your feedback @ha-manel, But i have the grid attribute displayed in my css styling, you can kindly check my `project-container` class

2022-12-07 14:41 UTC, Abenezer-Tilahun approved these changes
Hi @EnixWord 
 
Your project is complete  👍 💯   There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 👏🏻

✔️ No linter errors.
✔️ You used correct GitHub-Flow.
✔️ Professional README  
✔️ Good Commit Messages


## Optional suggestions

- [ ] Kindly remove the duplicated READEME File you used.

https://github.com/EnixWord/My_Porfolio/blob/5017ba40ffd979cddecb6067129ed79e201f53fb/README.md?plain=1#L180-L228

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-07 14:41 UTC, Abenezer-Tilahun commented on index.html
> +            <p>Let's Connect</p>
- [ Optional ] Kindly i Recommend you use a header tag `hx` for  titles (e.g., "Let's connect"), This way it will be semantic correct.

2022-12-07 14:48 UTC, merged